import { Gear } from "@/types/gear";

export const featuredGear: Gear[] = [
  {
    id: "1",
    name: "Mountain Bike",
    description: "High-performance mountain bike for off-road trails.",
    brand: "Trek",
    price: "1200",
    stock: 5,
    avgRating: 4.8,
    available: true,
    images: ["/images/bike.jpg"],
    providerId: "p1",
    categoryId: "c1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: { name: "Cycling" },
    provider: { id: "p1", name: "Outdoor Gear BD" },
  },
  {
    id: "2",
    name: "Camping Tent",
    description: "4-person waterproof camping tent.",
    brand: "NatureHike",
    price: "900",
    stock: 3,
    avgRating: 4.5,
    available: true,
    images: ["/images/tent.jpg"],
    providerId: "p2",
    categoryId: "c2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: { name: "Camping" },
    provider: { id: "p2", name: "Camping Hub" },
  },
  {
    id: "3",
    name: "Football",
    description: "Professional grade football.",
    brand: "Nike",
    price: "300",
    stock: 10,
    avgRating: 4.2,
    available: false,
    images: ["/images/football.jpg"],
    providerId: "p3",
    categoryId: "c3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: { name: "Sports" },
    provider: { id: "p3", name: "Sports World" },
  },
  {
    id: "4",
    name: "Kayak",
    description: "Single person kayak for water adventures.",
    brand: "Aqua",
    price: "1800",
    stock: 2,
    avgRating: 4.9,
    available: true,
    images: ["/images/kayak.jpg"],
    providerId: "p4",
    categoryId: "c4",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: { name: "Water Sports" },
    provider: { id: "p4", name: "Aqua Rentals" },
  },
  {
    id: "5",
    name: "Climbing Rope",
    description: "60m dynamic climbing rope.",
    brand: "Black Diamond",
    price: "500",
    stock: 8,
    avgRating: 4.7,
    available: true,
    images: ["/images/rope.jpg"],
    providerId: "p5",
    categoryId: "c5",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: { name: "Climbing" },
    provider: { id: "p5", name: "Climb Safe" },
  },
  {
    id: "6",
    name: "Basketball",
    description: "Indoor/outdoor basketball.",
    brand: "Wilson",
    price: "250",
    stock: 12,
    avgRating: 4.3,
    available: true,
    images: ["/images/basketball.jpg"],
    providerId: "p6",
    categoryId: "c3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: { name: "Sports" },
    provider: { id: "p6", name: "Sports World" },
  },
];